export type Result = {
  name: string;
  side: 'low' | 'high';
  type: 'ingredient';
  cat: string;
};
export const data: Result[] = [
  {
    name: 'Bamboo shoots',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Bean sprouts',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Broccoli (3/4 cup)',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Cabbage, common and red (3/4 cup)',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Carrots',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Celery (less than 5cm stalk)',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Chick peas (1/4 cup max)',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Corn (1/2 cob max)',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Courgette / Zucchini (65g)',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Cucumber',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Eggplant (1 cup)',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Green beans',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Green pepper (1/2 cup)',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Kale',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Lettuce e.g. Butter, iceberg, rocket',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Parsnip',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Potato',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Pumpkin',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Red peppers',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Scallions / spring onions (green part)',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Squash',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Sweet potato (1/2 cup)',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Tomatoes (1 small)',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Turnip (1/2 turnip)',
    side: 'low',
    type: 'ingredient',
    cat: 'Vegetables and Legumes',
  },
  {
    name: 'Bananas, unripe (1 medium)',
    side: 'low',
    type: 'ingredient',
    cat: 'Fruit',
  },
  {
    name: 'Blueberries (1/4 cup)',
    side: 'low',
    type: 'ingredient',
    cat: 'Fruit',
  },
  {
    name: 'Cantaloupe (3/4 cup)',
    side: 'low',
    type: 'ingredient',
    cat: 'Fruit',
  },
  { name: 'Cranberry', side: 'low', type: 'ingredient', cat: 'Fruit' },
  { name: 'Clementine', side: 'low', type: 'ingredient', cat: 'Fruit' },
  { name: 'Grapes', side: 'low', type: 'ingredient', cat: 'Fruit' },
  {
    name: 'Melons e.g. Honeydew, Galia (1/2 cup)',
    side: 'low',
    type: 'ingredient',
    cat: 'Fruit',
  },
  {
    name: 'Kiwifruit (2 small)',
    side: 'low',
    type: 'ingredient',
    cat: 'Fruit',
  },
  { name: 'Lemon', side: 'low', type: 'ingredient', cat: 'Fruit' },
  { name: 'Orange', side: 'low', type: 'ingredient', cat: 'Fruit' },
  { name: 'Pineapple', side: 'low', type: 'ingredient', cat: 'Fruit' },
  {
    name: 'Raspberry (30 berries)',
    side: 'low',
    type: 'ingredient',
    cat: 'Fruit',
  },
  { name: 'Rhubarb', side: 'low', type: 'ingredient', cat: 'Fruit' },
  { name: 'Strawberry', side: 'low', type: 'ingredient', cat: 'Fruit' },
  { name: 'Beef', side: 'low', type: 'ingredient', cat: 'Meats & Substitutes' },
  {
    name: 'Chicken',
    side: 'low',
    type: 'ingredient',
    cat: 'Meats & Substitutes',
  },
  { name: 'Lamb', side: 'low', type: 'ingredient', cat: 'Meats & Substitutes' },
  { name: 'Pork', side: 'low', type: 'ingredient', cat: 'Meats & Substitutes' },
  {
    name: 'Quorn mince',
    side: 'low',
    type: 'ingredient',
    cat: 'Meats & Substitutes',
  },
  {
    name: 'Cold cuts e.g. Ham and turkey breast',
    side: 'low',
    type: 'ingredient',
    cat: 'Meats & Substitutes',
  },
  {
    name: 'Oats',
    side: 'low',
    type: 'ingredient',
    cat: 'Breads, Cereals, Grains and Pasta',
  },
  {
    name: 'Quinoa',
    side: 'low',
    type: 'ingredient',
    cat: 'Breads, Cereals, Grains and Pasta',
  },
  {
    name: 'Gluten free foods e.g. breads, pasta',
    side: 'low',
    type: 'ingredient',
    cat: 'Breads, Cereals, Grains and Pasta',
  },
  {
    name: 'Savory biscuits',
    side: 'low',
    type: 'ingredient',
    cat: 'Breads, Cereals, Grains and Pasta',
  },
  {
    name: 'Buckwheat',
    side: 'low',
    type: 'ingredient',
    cat: 'Breads, Cereals, Grains and Pasta',
  },
  {
    name: 'Chips / crisps (plain)',
    side: 'low',
    type: 'ingredient',
    cat: 'Breads, Cereals, Grains and Pasta',
  },
  {
    name: 'Cornflour',
    side: 'low',
    type: 'ingredient',
    cat: 'Breads, Cereals, Grains and Pasta',
  },
  {
    name: 'Oatmeal (1/2 cup max)',
    side: 'low',
    type: 'ingredient',
    cat: 'Breads, Cereals, Grains and Pasta',
  },
  {
    name: 'Popcorn',
    side: 'low',
    type: 'ingredient',
    cat: 'Breads, Cereals, Grains and Pasta',
  },
  {
    name: 'Pretzels',
    side: 'low',
    type: 'ingredient',
    cat: 'Breads, Cereals, Grains and Pasta',
  },
  {
    name: 'Rice e.g. Basmati, brown, white',
    side: 'low',
    type: 'ingredient',
    cat: 'Breads, Cereals, Grains and Pasta',
  },
  {
    name: 'Tortilla chips',
    side: 'low',
    type: 'ingredient',
    cat: 'Breads, Cereals, Grains and Pasta',
  },
  {
    name: 'Almonds (max of 10)',
    side: 'low',
    type: 'ingredient',
    cat: 'Nuts & Seeds',
  },
  { name: 'Chestnuts', side: 'low', type: 'ingredient', cat: 'Nuts & Seeds' },
  { name: 'Hazelnuts', side: 'low', type: 'ingredient', cat: 'Nuts & Seeds' },
  {
    name: 'Macademia nuts',
    side: 'low',
    type: 'ingredient',
    cat: 'Nuts & Seeds',
  },
  { name: 'Peanuts', side: 'low', type: 'ingredient', cat: 'Nuts & Seeds' },
  {
    name: 'Pecans (10 halves)',
    side: 'low',
    type: 'ingredient',
    cat: 'Nuts & Seeds',
  },
  { name: 'Poppy seeds', side: 'low', type: 'ingredient', cat: 'Nuts & Seeds' },
  {
    name: 'Pumpkin seeds',
    side: 'low',
    type: 'ingredient',
    cat: 'Nuts & Seeds',
  },
  {
    name: 'Sesame seeds',
    side: 'low',
    type: 'ingredient',
    cat: 'Nuts & Seeds',
  },
  {
    name: 'Sunflower seeds',
    side: 'low',
    type: 'ingredient',
    cat: 'Nuts & Seeds',
  },
  { name: 'Walnuts', side: 'low', type: 'ingredient', cat: 'Nuts & Seeds' },
  { name: 'Almond milk', side: 'low', type: 'ingredient', cat: 'Milk' },
  {
    name: 'Coconut milk (125ml)',
    side: 'low',
    type: 'ingredient',
    cat: 'Milk',
  },
  { name: 'Hemp milk (125ml)', side: 'low', type: 'ingredient', cat: 'Milk' },
  { name: 'Lactose free milk', side: 'low', type: 'ingredient', cat: 'Milk' },
  { name: 'Oat milk (30ml max)', side: 'low', type: 'ingredient', cat: 'Milk' },
  { name: 'Rice milk', side: 'low', type: 'ingredient', cat: 'Milk' },
  {
    name: 'Soya milk made with soy protein',
    side: 'low',
    type: 'ingredient',
    cat: 'Milk',
  },
  { name: 'Butter', side: 'low', type: 'ingredient', cat: 'Dairy & Eggs' },
  {
    name: 'Dark chocolate (5 squares)',
    side: 'low',
    type: 'ingredient',
    cat: 'Dairy & Eggs',
  },
  { name: 'Eggs', side: 'low', type: 'ingredient', cat: 'Dairy & Eggs' },
  {
    name: 'Milk chocolate (4 squares max)',
    side: 'low',
    type: 'ingredient',
    cat: 'Dairy & Eggs',
  },
  {
    name: 'White chocolate (3 squares max)',
    side: 'low',
    type: 'ingredient',
    cat: 'Dairy & Eggs',
  },
  { name: 'Brie', side: 'low', type: 'ingredient', cat: 'Cheese' },
  { name: 'Camembert', side: 'low', type: 'ingredient', cat: 'Cheese' },
  { name: 'Cheddar', side: 'low', type: 'ingredient', cat: 'Cheese' },
  { name: 'Cottage cheese', side: 'low', type: 'ingredient', cat: 'Cheese' },
  { name: 'Feta', side: 'low', type: 'ingredient', cat: 'Cheese' },
  { name: 'Mozzarella', side: 'low', type: 'ingredient', cat: 'Cheese' },
  { name: 'Parmesan', side: 'low', type: 'ingredient', cat: 'Cheese' },
  { name: 'Swiss', side: 'low', type: 'ingredient', cat: 'Cheese' },
  {
    name: 'Barbeque sauce (check ingredients)',
    side: 'low',
    type: 'ingredient',
    cat: 'Condiments',
  },
  {
    name: 'Chutney (1 tbsp max)',
    side: 'low',
    type: 'ingredient',
    cat: 'Condiments',
  },
  {
    name: 'Garlic infused oil',
    side: 'low',
    type: 'ingredient',
    cat: 'Condiments',
  },
  {
    name: 'Golden syrup (1 tsp)',
    side: 'low',
    type: 'ingredient',
    cat: 'Condiments',
  },
  {
    name: 'Strawberry and raspberry jam / jelly',
    side: 'low',
    type: 'ingredient',
    cat: 'Condiments',
  },
  { name: 'Mayonnaise', side: 'low', type: 'ingredient', cat: 'Condiments' },
  { name: 'Mustard', side: 'low', type: 'ingredient', cat: 'Condiments' },
  { name: 'Soy sauce', side: 'low', type: 'ingredient', cat: 'Condiments' },
  { name: 'Tomato sauce', side: 'low', type: 'ingredient', cat: 'Condiments' },
  { name: 'Aspartame', side: 'low', type: 'ingredient', cat: 'Sweeteners' },
  { name: 'Acesulfame K', side: 'low', type: 'ingredient', cat: 'Sweeteners' },
  { name: 'Glucose', side: 'low', type: 'ingredient', cat: 'Sweeteners' },
  { name: 'Saccharine', side: 'low', type: 'ingredient', cat: 'Sweeteners' },
  { name: 'Stevia', side: 'low', type: 'ingredient', cat: 'Sweeteners' },
  { name: 'Sucralose', side: 'low', type: 'ingredient', cat: 'Sweeteners' },
  {
    name: 'Sugar / sucrose',
    side: 'low',
    type: 'ingredient',
    cat: 'Sweeteners',
  },
  { name: 'Beer (one max)', side: 'low', type: 'ingredient', cat: 'Drinks' },
  { name: 'Coffee, black', side: 'low', type: 'ingredient', cat: 'Drinks' },
  {
    name: 'Drinking chocolate powder',
    side: 'low',
    type: 'ingredient',
    cat: 'Drinks',
  },
  { name: 'Herbal tea (weak)', side: 'low', type: 'ingredient', cat: 'Drinks' },
  {
    name: 'Orange juice (125ml max)',
    side: 'low',
    type: 'ingredient',
    cat: 'Drinks',
  },
  { name: 'Peppermint tea', side: 'low', type: 'ingredient', cat: 'Drinks' },
  { name: 'Water', side: 'low', type: 'ingredient', cat: 'Drinks' },
  { name: 'Wine (one max)', side: 'low', type: 'ingredient', cat: 'Drinks' },
];
